### ISSUE TITLE
Cracking sound due to cut sound samples

### ISSUE THREAD

**Issue by manumeter** [beatboxjs/beatbox.js#19]
We've noticed that, if the same sound sample is played repeatedly in a sequence, the currently playing sample gets cut as soon as the next one starts. This can cause cracking sounds (especially noticeable on damp sounds and high tempo).

I've tested the following patch, and had the feeling that it improves this situation a lot:

```diff
diff --git a/src/beatbox.ts b/src/beatbox.ts
index 5f87ba8..35a38f7 100644
--- a/src/beatbox.ts
+++ b/src/beatbox.ts
@@ -73,9 +73,6 @@ export class Beatbox extends EventEmitter {
        /** The this._audioContext.currentTime of the start of the last bar that was created by the cache (excluding upbeat) */
        _referenceTime: number | null = null;
 
-       /** Last sound objects of each instrument while filling the cache */
-       _lastInstrumentStrokes: { [instr: string]: ScheduledSound } = { };
-
        constructor(pattern: Pattern, strokeLength: number, repeat: boolean, upbeat?: number) {
                super();
 
@@ -372,12 +369,7 @@ export class Beatbox extends EventEmitter {
                                        const instr = Beatbox._resolveInstrument(part[strokeIdx]);
                                        if (instr && (instr.volume == null || instr.volume > 0)) {
                                                let time = this._referenceTime! + (this._position - this._upbeat) * this._strokeLength / 1000;
-
-                                               if(this._lastInstrumentStrokes[instr.key])
-                                                       this._lastInstrumentStrokes[instr.key].stop(time);
-
                                                const sound = this._scheduleSound(instr, time);
-                                               this._lastInstrumentStrokes[instr.key] = sound;
                                        }
                                }
                        }

```

So I was wondering what the reason for this code is. Did you have issues with overlapping sound samples? If there is no downside, could it be removed?

I've attached two examples to illustrate the issue (one with the original code, one with the patch from above applied).

[General Breaks - 8 down (patched).mp3](https://github.com/user-attachments/files/22532555/General.Breaks.-.8.down.patched.mp3)
[General Breaks - 8 down.mp3](https://github.com/user-attachments/files/22532556/General.Breaks.-.8.down.mp3)

Thanks a lot (:

**Comment by cdauth** [comment]
This is also addressed in #18, but I never found the time to look into it.

The reason why this was implemented was that we were using some samples of a big drum whose skin was resonating for a very very long time. Without cutting the previous sound when a new one was played, the reverb of those sounds would accumulate and eventually you would only hear one loud reverb instead of the actual hits of the drum. For a drum, I found this unrealistic: When you hit the drum, it kills the resonance of the previous hit. That’s why I implemented this.

I see that there are some use cases where this functionality is needed differently. On the other hand, I see that there might be some cases where a previous sound should be cut even when there is no new sound of the same type (such as when dampening a piano, or when a different type of stroke is played on the same instrument).

I think there should be an option to control the behaviour for each sound. One idea would be:
* Simple syntax: `"snare"` cuts previous snare and plays a new one, `"-snare"` only cuts previous snare, `"+snare"` plays new snare without cutting previous
* Extended syntax `{ instrument: "snare", cut: -1 }` only cuts, `cut: 0` cuts and plays, `cut: 1` only plays

What do you think about this? Suggestions are welcome.


For the specific 8-down break, I'm wondering if there isn't another way to solve the issue, such as quickly fading out the sound instead of hardly cutting it. Because as mentioned, for a single drum it is more realistic to cut the previous sound when a new one is played.

**Comment by manumeter** [comment]
Ah sorry, I didn't notice the PR.

Okay, I see. So yes in that case, quickly fading out instead of cutting it hard would probably be a nice replacement to solve the cracking sound but still not having the loud accumulated reverb. Unfortunately, I don't have an idea how to do that, yet - but I can have a deeper look into the code and try to find out.

And in the long run, I guess the nicest solution would be what you suggested: a way to control the behavior in the calling code. In the context of drumming, it would make sense to have a different behavior per stroke, for example: a regular stroke would stop the previous one, a dampened stroke too, but rim clicks and such would not influence the previous hit. To get it 100% realistic would make it quite complicated though (because dampened and regular strokes would influence each other, stick or rim clicks would not). But in my opinion, this would give only very little benefit and thus wouldn't justify a huge increase of complexity.

So for me, the quick fade-out solution would already be good enough for now. I'll have a look into it if you also think that this would be a good solution for now.

**Comment by cdauth** [comment]
I haven’t worked with the Web Audio API for a while, so I would have to invest some time to find a solution for the fade-out. But I briefly looked into it and have a rough idea how it could be done.

We are already piping the sound through a `GainNode` if the sound has a custom volume. To implement the fade-out, we should _always_ pipe it through a `GainNode`.

Now, the [`GainNode`](https://developer.mozilla.org/en-US/docs/Web/API/GainNode) documentation says: “If modified, the new gain is instantly applied, causing unaesthetic 'clicks' in the resulting audio. To prevent this from happening, never change the value directly but use the exponential interpolation methods on the [`AudioParam`](https://developer.mozilla.org/en-US/docs/Web/API/AudioParam) interface.” So I think before stopping the sound using `sound.stop(time)`, we probably need to call something like `gainNode.gain.exponentialRampToValueAtTime(0.01, time)` (apparently using `0` does not work for exponential transitions). Since the transition starts at the time of the previous event, we probably need to call `gainNode.gain.setValueAtTime(volume, time - 0.1)` to mark the start of the transition. We can experiment with the exact duration of the transition, `0.1` seconds is only a suggestion.

I don’t have much time working on this right now. If you have the time to implement this, feel free to experiment with it an open a pull request. If you don’t have time, I can try to look into it at some point.

The thing about making the cut-off configurable we can look at another time.

**Comment by manumeter** [comment]
So here's a possible implementation of the fade out solution:

```patch
diff --git a/src/beatbox.ts b/src/beatbox.ts
index 5f87ba8..cf891d7 100644
--- a/src/beatbox.ts
+++ b/src/beatbox.ts
@@ -18,6 +18,7 @@ export interface ScheduledSound {
 	duration: number;
 	source: AudioBufferSourceNode;
 	stop(time?: number): void;
+	rampTo(volume: number, duration: number, time?: number): void;
 	clearTimeout: number;
 }
 
@@ -110,14 +111,11 @@ export class Beatbox extends EventEmitter {
 		const source = this._audioContext!.createBufferSource();
 		source.buffer = instrument.audioBuffer;
 
-		if (instrument.volume && instrument.volume != 1) {
-			const gainNode = this._audioContext!.createGain();
+		const gainNode = this._audioContext!.createGain();
+		if (instrument.volume && instrument.volume != 1)
 			gainNode.gain.value = instrument.volume;
-			gainNode.connect(this._audioContext!.destination);
-			source.connect(gainNode);
-		} else {
-			source.connect(this._audioContext!.destination);
-		}
+		gainNode.connect(this._audioContext!.destination);
+		source.connect(gainNode);
 
 		source.start(time);
 
@@ -139,11 +137,20 @@ export class Beatbox extends EventEmitter {
 			}
 		};
 
+		const rampTo = (volume: number, duration: number, time?: number) => {
+			const now = this._audioContext!.currentTime;
+			const t = time != null && time > 0 ? time : now;
+			gainNode.gain.cancelScheduledValues(t);
+			gainNode.gain.setValueAtTime(gainNode.gain.value, t);
+			gainNode.gain.linearRampToValueAtTime(volume, t + duration);
+		};
+
 		const sound: ScheduledSound = {
 			time,
 			duration: instrument.audioBuffer.duration,
 			source,
 			stop,
+			rampTo,
 			clearTimeout: window.setTimeout(clear, (time - this._audioContext!.currentTime + instrument.audioBuffer.duration) * 1000)
 		};
 		this._scheduledSounds.push(sound);
@@ -374,7 +381,7 @@ export class Beatbox extends EventEmitter {
 						let time = this._referenceTime! + (this._position - this._upbeat) * this._strokeLength / 1000;
 
 						if(this._lastInstrumentStrokes[instr.key])
-							this._lastInstrumentStrokes[instr.key].stop(time);
+							this._lastInstrumentStrokes[instr.key].rampTo(0, 0.01, time);
 
 						const sound = this._scheduleSound(instr, time);
 						this._lastInstrumentStrokes[instr.key] = sound;
```

I've tested it with different times. To prevent the cracking sound but still avoid a most of the accumulated reverb, I found 0.01s to be good value (see attached sound samples for some different values).

What do you think?

[General.Breaks.-.8.down.0.01s.fadeout.mp3](https://github.com/user-attachments/files/22658464/General.Breaks.-.8.down.0.01s.fadeout.mp3)
[General.Breaks.-.8.down.0.30s.fadeout.mp3](https://github.com/user-attachments/files/22658465/General.Breaks.-.8.down.0.30s.fadeout.mp3)
[General.Breaks.-.8.down.0.02s.fadeout.mp3](https://github.com/user-attachments/files/22658462/General.Breaks.-.8.down.0.02s.fadeout.mp3)
[General.Breaks.-.8.down.0.10s.fadeout.mp3](https://github.com/user-attachments/files/22658463/General.Breaks.-.8.down.0.10s.fadeout.mp3)
[General.Breaks.-.8.down.0.00s.fadeout.mp3](https://github.com/user-attachments/files/22658461/General.Breaks.-.8.down.0.00s.fadeout.mp3)

**Comment by cdauth** [comment]
Thanks for your contribution. I have merged your pull request and made some modifications to the code. In your code you distinguished between `.stop()` and `.rampTo()`. I have modified it so that `.stop()` is always used again and always fades out the sound, also when the player is manually stopped. I don’t know if I’m imagining it, but I think there used to be a click sometimes when manually stopping the song, and now the click is gone. I would be glad if you could test my changes and see if they work for you as intended. I will also make a few more modifications to the library that I would be glad if you could test them. The plan is to release v5 soon.

I am curious about why you used `.linearRampToValueAtTime()` rather than `.exponentialRampToValueAtTime()` as recommended on MDN. Did you try both and found a benefit to using the linear ramp?

**Comment by cdauth** [comment]
v5.0.0 is released now. Feel free to give feedback, if anything isn’t right, I can make another release.

**Comment by manumeter** [comment]
Great, thanks a lot for merging and optimizing! (I didn't know `exponentialRampToValueAtTime` is the recommended way, so no particular reason for my choice, just a lack of knowledge I would say.)

I've finally also tested it now, and it sounds good! (I just noticed that it still cracks when changing the tempo while playing - but I never had the idea to test this before. That was the only way for me to produce cracking sounds now.)

**Comment by manumeter** [comment]
Hmm, I got feedback from users now that they experience (a lot of) cracking sounds when changing the volume/speed during playback. Could it be that we have to add the `rampTo()` function on more places in the code?

**Comment by cdauth** [comment]
I think there is a problem with the scheduling in `_applyChanges()`. I have noticed it as well. I think the problem is not the cracking, but the fact that the same stroke is scheduled multiple times at once when sliding the volume/speed. I will try to work on a fix soon.
